export interface YoutubeSearchResultItem {
  id: string;
  title: string;
  url: string;
  channelTitle?: string;
  channelUrl?: string;
  durationSeconds?: number;
  durationFormatted?: string;
  viewCount?: number;
  uploadDate?: string;
  descriptionSnippet?: string;
}

export interface YoutubeSearchOptions {
  query: string;
  limit?: number;
  type?: "video" | "channel" | "playlist";
  timeoutMs?: number;
}

export interface YoutubeVideoDetails {
  id: string;
  title: string;
  url: string;
  channelTitle: string;
  channelUrl?: string;
  description: string;
  durationSeconds?: number;
  durationFormatted?: string;
  viewCount?: number;
  likeCount?: number;
  uploadDate?: string;
  tags?: string[];
  chapters?: Array<{ title: string; startTime: number; endTime?: number }>;
  availableSubtitles?: string[];
  availableAutoSubtitles?: string[];
}

export interface YoutubeTranscriptOptions {
  urlOrId: string;
  language?: string; // default: "es,en"
  clean?: boolean; // default: true
  timeoutMs?: number;
}

export interface YoutubeTranscriptResult {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  transcriptText: string;
  byteSize: number;
}

export interface YoutubeChannelInfo {
  id: string;
  title: string;
  url: string;
  description?: string;
  subscriberCount?: number;
}
